### ISSUE TITLE
Use new R3E flag data

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#101]
R3E has added yellowPositionsGained (the number of positions you have gained illegally under yellow flag to give back) and much more specific warning and penalty data for ignoring blue and yellow flags. The app needs to map these and use them. Does RF2 or RF1 expose anything like this?

**Comment by mrbelowski** [comment]
Done the first cut of this, can't be arsed to keep bashing away at it so I'll call it "done" for now

**Comment by TheIronWolfModding** [comment]
Unfortunately I don't think rF1/rF2 has this (so R3E kicks ass hee), but it might have something related to violating order during FCY.  In time, I'll get to it.
