### ISSUE TITLE
sort out UI scaling

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#11]

**Comment by mrbelowski** [comment]
this will probably be deferred indefinitely because I hate UI work and suck at it

**Comment by TheIronWolfModding** [comment]
Actually, if this is regarding 2k/4k display, this is not necessary on Win8/Win10.  Just select override application scaling in .exe properties, and it scales nicely.  I've added FAQ entry for that.

**Comment by mrbelowski** [comment]
closing this because it's so indescribably boring I don't even want toi think about it
