### ISSUE TITLE
Feature request: Set audio device

### ISSUE THREAD

**Issue by tapanij** [mrbelowski/CrewChiefV4#113]
In assetto corsa with the audio app you can set a playback device, I do that to make AC audio play through non-default device, but then crew chief is in a separate audio device and I can't change volumes together with AC and CC. 

It's a problem because I also listen to music / play twitch while so I have to reserve default audio device for that and I change its volume during racing but then for example if I want to mute music then crew chief gets muted also.

3rd party audio routing softwares didn't work with crew chief.

**Comment by TheIronWolfModding** [comment]
Please see this.  Works with Audio Router:
http://thecrewchief.org/showthread.php?125-Routing-game-audio-to-a-different-output-device&p=1372#post1372

**Comment by tapanij** [comment]
In my case that solution isn't useful. I need to play game audio and crew chief in a **secondary** audio device so I can have background music / podcast whatever in the default device so I can change that volume while driving with volume up/down buttons on my wheel.

**Comment by TheIronWolfModding** [comment]
Version 4.8.1.9 adds nAudio support which enables this scenario.
