### ISSUE TITLE
thecrewchief.org 403 error

### ISSUE THREAD

**Issue by darkdiesel** [mrbelowski/CrewChiefV4#143]
Hi. I can't open site http://thecrewchief.org. 403 Error appears.

**Comment by TheIronWolfModding** [comment]
No repro.

**Comment by Sparten** [comment]
We are going to need your ip so we can allow it as we have blocked a wide nr if ranges comming from your region do to massive spam.

**Comment by darkdiesel** [comment]
Now works good.
