### ISSUE TITLE
network data mode changed

### ISSUE THREAD

**Issue by gcoulby** [mrbelowski/CrewChiefV4#172]
Hi Jim, 

I have just got a comment on the Steam guide I made regarding the 'pCARS and pCARS2 (network data)'

The latest update has pCARS (network data) and pCars2 without the UDP controller in the bottom left. If we want to use network data do we have to use the pCars1 option?

Is it possible to reinstate this option?

**Comment by mrbelowski** [comment]
yes, if you want to use network data in pCARS2 you have to use pCARS1 mode. The pCARS2 UDP data is still too buggy to use. I've implemented it but it really doesn't work properly so it's unavailable, When SMS sort out the many issues I'll finish the Crew Chief implementation
