### ISSUE TITLE
Request: Select sound devices

### ISSUE THREAD

**Issue by radical-equanimity** [mrbelowski/CrewChiefV4#196]
Using Windows 10, I need to switch to Oculus Rift for default playback/recording device before launching CC. Then have to switch back to regular headphones & microphone for regular desktop work. Would be great to be able to select the device rather than assuming default device

**Comment by mrbelowski** [comment]
you can do this for the playback device - enable the "Use nAudio playback" option in the Properties screen. The recording device has to be default

**Comment by radical-equanimity** [comment]
Thanks, that helps with half the problem. I've cloned and can build the solution. Where is the sound recorder instantiated in code, so that I can play around with modifying the input device

**Comment by mrbelowski** [comment]
Exactly. It's not that it can't be done, it's that it would need a substantial amount of rework in the speech recogniser stuff to get the audio from a (nAudio) wave stream

**Comment by radical-equanimity** [comment]
OK.. I think I've done some of the legwork to get this working but still getting errors about No Input Device selected when I click "start application". If you have time to check out my fork/branch-
https://github.com/radical-equanimity/CrewChiefV4/tree/rec_dev

**Comment by radical-equanimity** [comment]
In my rec_dev branch I've worked out how to get any recording device to feed the Speech Recognizer,  but only using the Hold Button mode. To get it working, I had to change what SpeechRecognizer.recognizeAsync() and SpeechRecognizer.recognizeAsyncCancel() actually do.

**Comment by mrbelowski** [comment]
Fantastic, I'll take a closer look at this today or tomorrow - I've got a lot of boring work stuff to get through first. I'll get back to you.
