### ISSUE TITLE
pcars2 collision magnitude tuning

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#240]
Still getting 'good pass' messages with max collision threshold at 0.1, probably need to reduce this and test a bit by bouncing off the ai

**Comment by TheIronWolfModding** [comment]
2cents - in rf2 implementation there's no min collision threshold - any contact is dirty racing.

**Comment by Sparten** [comment]
Was also watching a stream where the guy got the good pass message even though the other guy was off track, i think we might need to add a few more checks for this.

**Comment by mrbelowski** [comment]
it's not that I don't trust PCars2's data, but I don't trust PCars2's data. I'll reduce the collision magnitude threshold and do a bit of testing, but I'm not convinced we'll be able to filter out bump-n-run passes without disabling this entirely.

Establishing if an opponent is off-track isn't really possible for some games (pcars, r3e). The app currently checks if there's a high speed difference between the 2 cars and disables 'good pass' messages in this case, which catches a lot of cases where an opponent is off track when you pass him
