### ISSUE TITLE
add the SRE to be configured to always listen, except when a button it pressed

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#243]
need to investigate this one a bit, especially now we might also be using nAudio

**Comment by Sparten** [comment]
Could also make a code word, so if always on is selected, and a code word is set it needs to be said before reacting to voice inputs.

**Comment by mrbelowski** [comment]
the android app has that, because it uses free-diction (can recognise anything). We could include it in the PC app but I'm looking to do as little work as humanly possible here :)

**Comment by Sparten** [comment]
true, looking at it, it would need to be added to all the gramma.

**Comment by mrbelowski** [comment]
latest version (released this week) has a 'trigger word' SRE feature so i'm closing this ticket
