### ISSUE TITLE
fix command to enable/disable yellow flags

### ISSUE THREAD

**Issue by radical-equanimity** [mrbelowski/CrewChiefV4#257]
Problem: In Assetto Corsa and R3E, I've noticed the engineer does not announce incidents/ yellow flags even when he's acknowledged that he will. However, he does announce deltas if I ask him to do that

Reproduce: Tell engineer to "Keep Quiet." After he acknowledges ask him to "give me yellows" and wait for someone to go off track ahead

**Comment by mrbelowski** [comment]
This is kind of by design. Admittedly a "shit" design. The "give me yellows" is a toggle to switch yellow reporting on / off when it's part of the regular CC messages. The keep-quiet command overrides this even when "give me yellow" is requested after "keep quiet". I'll have a think about it
