### ISSUE TITLE
%AppData%\local* loop

### ISSUE THREAD

**Issue by AtzeBK** [mrbelowski/CrewChiefV4#259]
Hello, 
you created a loop in path %appdata%\local*. 
There are many subfolders named appdata (maybe translated incorrect, my German Folders are named "Anwendungsdaten"). 
For example: 
C:\Users\USERNAME\AppData\Local\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\Anwendungsdaten\CrewChiefV4\sounds\voice\spotter_Ross\

**Comment by mrbelowski** [comment]
so it wasn't an issue then? I've never seen the app do this, and don't know how it would be possible

**Comment by AtzeBK** [comment]
No, it wasn't. There was a shortcut content I copied with robocopy in a loop. My mistake, no issue with the app I think. Sorry for confusion and mistakenly reporting that as an issue.
