### ISSUE TITLE
add metadata to singleSound object

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#276]
the playback code is given (eventually...) a SingleSound object to play. These are instantiated at startup time and are reused so are immutable. In some cases we want to have additional contextual information with these SingleSound objects. Suggest we pass around a wrapper object instead here, which contains the SingleSound and a bunch of meta data.

Meta data includes: 

message_id (incrementing int / long, unique, allows a sound to be cancelled if other sounds in the same message have been blocked in the playback moderator)
message_type (we know if the sound is spotter / beep, but also worth knowing if the sound is a voice comms response, a yellow flag message, or some other data so the moderator can make a more informed choice as to whether to drop it. Perhaps this could be 'priority' instead)

Other stuff?

**Comment by TheIronWolfModding** [comment]
Additional metadata: text representation of a sound.  Subtitles have been requested many times, and I think SimHub dev will gladly add overlay if we expose phrases.  But, it is a lot of work.

**Comment by mrbelowski** [comment]
yes, sounds like a separate issue - will close this one
