### ISSUE TITLE
Button Assignment not working 

### ISSUE THREAD

**Issue by MerlinCooper** [mrbelowski/CrewChiefV4#296]
Some controllers do permanently sent a button pressed command (e.g. Fanatec MCLaren GT3 Wheel). Crew Chief immediately recognizes this button and therefore no other button could be assigned e.g. for talk to crew chief.

**Comment by TheIronWolfModding** [comment]
This is not an issue with Crew Chief, you need to change configuration of your rim, see here for instruuctions;
https://forum.sector3studios.com/index.php?threads/mclaren-650s-gt3-steering-wheel.8455/page-4#post-149633
