### ISSUE TITLE
iRacing fuel calculator not working

### ISSUE THREAD

**Issue by MatteAce** [mrbelowski/CrewChiefV4#316]
in iRacing, private test session or public practice session - I haven't tried on a race but I'd expect it to work the same

to reproduce:
voice recognition "chief, calculate fuel for 10 laps"

expected answer:
"we estimate 12 laps of fuel"

received answer:
fuel estimate "you have 15 minutes of fuel left, you use 1.1 liters per lap"

console log:
06:40:40.408 : Recognised : calcola benzina per dieci giri confidence = 0.865 [calculate fuel for 10 laps]
06:40:40.915 : Waiting for trigger word ehi capo [hey chief]
06:40:41.326 : Playing sounds, events: COMPOUND_Fuel/estimate, COMPOUND_Fuel/mean_use_per_lap
06:40:41.328 : (fuel/we_estimate, numbers_it/15, fuel/minutes_remaining)
06:40:45.807 : (numbers_it/1, numbers/point, numbers_it/1, fuel/litres_per_lap)

**Comment by mrbelowski** [comment]
this is actually an issue in the way the selected event chooses the correct action to invoke, and it's specific to the Italian translation Matteo is working on. I think I've fixed it for the fuel event
