### ISSUE TITLE
threading issues on start and stop app

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#320]
The start / stop button is clickable before the start / stop work has been completed. This makes it easy to crash the app by clicking furiously on it.

The SRE, AudioPlayer and main CC thread startup / shutdown tasks need to be complete before this button is re-enabled.

There's some refactoring work needed here to clean up the way these threads are managed

**Comment by TheIronWolfModding** [comment]
In master
