### ISSUE TITLE
2 liter threshold issues.

### ISSUE THREAD

**Issue by TheIronWolfModding** [mrbelowski/CrewChiefV4#351]
* This threshold should probably weighed somehow.    For Karts, it constantly generates too pessimistic message:
else if (currentGameState.FuelData.FuelLeft - fuelToEnd <= 2)
 {
      audioPlayer.playMessage(new QueuedMessage(RaceTime.folderHalfWayHome, 0, this), 7);
      audioPlayer.playMessage(new QueuedMessage(folderFuelWillBeTight, 0, this));
}

* For Karts or other fuel efficient vehicles, "2 liter warning" is not appropriate, probably, turn that off.

* We probably should turn "2 liters warning" in Qualification

Would appreciate your thoughts/ideas here.

**Comment by TheIronWolfModding** [comment]
Additionally, "5 minutes of fuel left" "half fuel used" are not required in qualification.  Maybe we should have option for fuel warnings in qualification?

**Comment by mrbelowski** [comment]
regarding qual and practice warnings, perhaps it makes more sense to prevent all the fuel warnings if we exit the pits with only 2 or 3 laps worth of fuel (as this is almost certainly a hot lap in qual or a qual simulation in practice)

**Comment by TheIronWolfModding** [comment]
I like that idea 👍

**Comment by mrbelowski** [comment]
Yes, I like it to. As this ticket is assigned to you, 'make it so' :P

**Comment by mrbelowski** [comment]
Should be just a case of changing that hard coded 2 for averageUsePerLap - will sort this today

**Comment by TheIronWolfModding** [comment]
Thanks Jim!
