### ISSUE TITLE
See if we can read slow down penalty info

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#363]
Maybe an initial call followed by 2 or 3 reminders as the time owed ticks down. If the data is available

**Comment by Sparten** [comment]
iRacing sends "blackflagfolded" when user have a slow down, and then you have to comply within a given time else it converts in to a drive-through.

**Comment by mrbelowski** [comment]
no data is available in R3E. There's a TimeDeduction integer, but I think this is just the time added at the end of a race for penalties (a whole number of seconds)

**Comment by mrbelowski** [comment]
we don't know how much time we need to give back, but I've added a 'you need to slow down or you'll get a penalty' message - this is only allowed to play once per lap
