### ISSUE TITLE
AC restart causes CTD v4.9.5.8

### ISSUE THREAD

**Issue by jackalope50** [mrbelowski/CrewChiefV4#365]
Clicking "start application" then "stop" it is ok. Clicking "start application" a second time causes CTD for game "assetto corsa (64 bit)". Changing game to iRacing or PCars does not duplicate the crash. 

Error logs:

- System 
  - Provider 
   [ Name]  Application Error 
  - EventID 1000 
   [ Qualifiers]  0 
   Level 2 
   Task 100 
   Keywords 0x80000000000000 
  - TimeCreated 
   [ SystemTime]  2018-11-16T15:22:20.656883400Z 
   EventRecordID 27920 
   Channel Application 
   Computer xxxxx 
   Security 
- EventData 
   CrewChiefV4.exe 
   1.0.0.0 
   5be4306b 
   KERNELBASE.dll 
   10.0.17134.407 
   99042cc0 
   e0434352 
   000000000003a388 
   748 
   01d47dc022279ac2 
   C:\Program Files (x86)\Britton IT Ltd\CrewChiefV4\CrewChiefV4.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   902b4833-bee2-4e20-91d5-1472cd36ed49 
        
Faulting application name: CrewChiefV4.exe, version: 1.0.0.0, time stamp: 0x5be4306b
Faulting module name: KERNELBASE.dll, version: 10.0.17134.407, time stamp: 0x99042cc0
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x748
Faulting application start time: 0x01d47dc022279ac2
Faulting application path: C:\Program Files (x86)\Britton IT Ltd\CrewChiefV4\CrewChiefV4.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 902b4833-bee2-4e20-91d5-1472cd36ed49
Faulting package full name: 
Faulting package-relative application ID: 

-----------------------------------------------------------------------------------------------------

- System 
  - Provider 
   [ Name]  .NET Runtime 
  - EventID 1026 
   [ Qualifiers]  0 
   Level 2 
   Task 0 
   Keywords 0x80000000000000 
  - TimeCreated 
   [ SystemTime]  2018-11-16T15:22:20.402938700Z 
   EventRecordID 27919 
   Channel Application 
   Computer XXXXX 
   Security 
- EventData 
   Application: CrewChiefV4.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ArgumentException at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource) at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean) at CrewChiefV4.assetto.ACSGameStateMapper..ctor() at CrewChiefV4.GameStateReaderFactory.getGameStateMapper(CrewChiefV4.GameDefinition) at CrewChiefV4.CrewChief.Run(System.String, Boolean) at CrewChiefV4.MainWindow.runApp() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()  

Application: CrewChiefV4.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at CrewChiefV4.assetto.ACSGameStateMapper..ctor()
   at CrewChiefV4.GameStateReaderFactory.getGameStateMapper(CrewChiefV4.GameDefinition)
   at CrewChiefV4.CrewChief.Run(System.String, Boolean)
   at CrewChiefV4.MainWindow.runApp()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by mrbelowski** [comment]
thanks for the info - this was fixed this afternoon and will be included in the next release

https://github.com/mrbelowski/CrewChiefV4/commit/839d1eb5b0c5172bca94f8ca6fd47f62d1d8e995
