### ISSUE TITLE
Not all actions have confirmation

### ISSUE THREAD

**Issue by movedoa** [mrbelowski/CrewChiefV4#367]
It would be nice to have an audible confirmation that the software understood what i said.
For example when i say ""pitstop clear tyres", the tires are cleared but i get no confirmation that that happened.

Best case would be "Cleared all tires" but i get that that is a massive amout of work.
"Understood" after every action would be good enough for me.

**Comment by mrbelowski** [comment]
all of the iRacing pit commands should have some acknowledge voice response - for example:
```
if (SpeechRecogniser.ResultContains(voiceMessage, SpeechRecogniser.PIT_STOP_CLEAR_TYRES))
{
  ClearTires();
  audioPlayer.playMessageImmediately(new QueuedMessage(AudioPlayer.folderAcknowlegeOK, 0));
  return;
}
```

so I'm not sure what's going on here - it works when i try it:

```
12:22:04.079 : Invoking speech recognition...
12:22:04.080 : Cancelling wait for speech
12:22:04.108 : Recognised : pitstop clear tyres confidence = 0.821
12:22:04.113 : matching entire response pitstop clear tyres
12:22:04.115 : PlaybackModerator: Opening radio channel as Chief
12:22:04.505 : Playing sounds, events: acknowledge/OK
12:22:04.506 : (acknowledge/OK)
12:22:05.207 : PlaybackModerator: Closing radio channel as Chief
```

**Comment by movedoa** [comment]
I will investigate some more in a few hours.
Will also append the log and my settings then. Maybe it some strange combination of settings on my end.

**Comment by movedoa** [comment]
Cannot reproduce this anymore, strange stuff.
Anyway sorry for the noise.
