### ISSUE TITLE
joystick button not responding

### ISSUE THREAD

**Issue by exenza** [mrbelowski/CrewChiefV4#369]
With a Fanatec CSL Elite + if CrewChief is open while the wheel is OFF it won't recognise key presses once the wheel is on, you always have to launch CrewChief AFTER you turned on the wheel.

**Comment by mrbelowski** [comment]
we're in the process of fixing this. Note we've migrated to gitlab now (https://gitlab.com/mr_belowski/CrewChiefV4/)
