### ISSUE TITLE
rF2 Inappropriate Message: After "Your suspension is destroyed", "Just settle down, find your rythm"

### ISSUE THREAD

**Issue by TheIronWolfModding** [mrbelowski/CrewChiefV4#89]

**Comment by mrbelowski** [comment]
might be able to close this - the app now purges any queued messages when severe damage is encountered, and if any component is destroyed it switches off any future pearls of wisdom for that session. Haven't tested of course. Our new corporate policies don't extend as far as actually testing :D

**Comment by TheIronWolfModding** [comment]
:)))) haha, what a nice way to start a day, reading those comments.

**Comment by TheIronWolfModding** [comment]
This is likely fixed by f4cdb5c5252ad58fe1f174b0f32e16c79ee2d1e0, thanks Jim.
