### ISSUE TITLE
Rework car class equality checks

### ISSUE THREAD

**Issue by mrbelowski** [mrbelowski/CrewChiefV4#94]
we're doing '==' comparison on the result of CarClassEnum.ToString(). This is still a bit risky because I'm not sure how enum.ToString() behaves with respect to String internment and object equality and really can't be arsed scrabbling through the arse-end of MickySoft's shitty C# documentation to work it out.

There's another issue here which needs to be considered. Some classes are 'almost equal' - e.g. R3E DTM2013, DTM2014, DTM2015, DTM2016. We may want to consider these as the same class for the purposes of lap time comparisons etc because they use the same physics and have similar performance characteristics.

We might be able to fix both these issues by having our own static IsSameClass(carClass1, carClass2) method on CarClass. This could do the necessary null checks and the String.Equals(carClass1.getCarClassIdentifier(), carClass2.getCarClassIdentifier()). It could also have special cases for these 'almost equal' car classes

**Comment by mrbelowski** [comment]
hacked together a quick-n-dirty implementation of this, will sanity check and commit later.

**Comment by TheIronWolfModding** [comment]
It appears that hack works nicely, the only thing to consider is possiblity of adding timingGroup to car class data, but that's a separate task and I can do it :)

**Comment by mrbelowski** [comment]
not sure if we need to do this at this stage because the grouping is only needed where we need distinct built-in (hard-coded) app behaviour while maintaining grouped behaviour for timing. It's a very game-specific (R3E) edge-case. If we externalise things like class-specific DRS rules we might need it, but I think this is quite a long way away

**Comment by TheIronWolfModding** [comment]
Yes, you're right, currently it is a special case, so let's do nothing - my favorite type of fix :)

**Comment by mrbelowski** [comment]
closing this. The solution is grotty but because this app isn't open source no one will ever find out ;)

**Comment by TheIronWolfModding** [comment]
yes, we should hide  the truth.
